project:
  type: website

website:
  title: "git4loek"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
bibliography: "/home/marvin/literature/zotero/references.bib"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



