project:
  type: website
  output-dir: docs
website:
  search: false
  navbar:
    left:
      - href: index.qmd
        text: What? and Why?
      - href: git_basics.qmd
        text: git & GitHub
      - href: git_rstudio.qmd
        text: RStudio Integration
      - href: git_examples.qmd
        text: Examples
      - href: readers.qmd
        text: Further Reading
    right: 
      - icon: github
        menu:
          - text: View on GitHub
            href:  https://github.com/LOEK-RS/git4loek
          - text: Other Courses
            href: https://teaching.mlspatial.org
bibliography: "/home/marvin/literature/zotero/references.bib"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




